/**
 * @suro-buya/cli - Scaffold Utilities
 * 
 * Utility functions for scaffolding universe templates.
 */

import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Template source directory
 */
const TEMPLATE_SOURCE = path.resolve(__dirname, '../../../templates/universe');

/**
 * Bible directory structure
 */
export const BIBLE_DIRECTORIES = [
  '01-character-bible',
  '02-world-bible',
  '03-story-bible',
  '04-visual-bible',
  '05-production-bible',
];

/**
 * Scaffold a new universe from template
 */
export async function scaffoldUniverse(
  targetDir: string,
  universeId: string,
  universeName: string,
  template: string = 'suro-buya'
): Promise<void> {
  const templatePath = path.join(TEMPLATE_SOURCE, 'src');
  const biblePath = path.join(targetDir, 'bible');
  
  // Create bible directories
  for (const dir of BIBLE_DIRECTORIES) {
    await fs.ensureDir(path.join(biblePath, dir));
  }
  
  // Copy template files if they exist
  if (await fs.pathExists(templatePath)) {
    await fs.copy(templatePath, path.join(targetDir, 'templates'), {
      overwrite: true,
    });
  }
  
  // Create universe.yaml template
  await createUniverseYaml(targetDir, universeId, universeName);
  
  // Create placeholder bible files
  await createPlaceholderBibleFiles(biblePath, universeId, universeName);
  
  // Create .gitignore
  await createGitignore(targetDir);
}

/**
 * Create universe.yaml manifest
 */
async function createUniverseYaml(
  targetDir: string,
  universeId: string,
  universeName: string
): Promise<void> {
  const manifest = `# Universe Manifest: ${universeName}
# Generated by suro-buya CLI
# Schema: packages/templates/universe/schema/metadata.md

id: "${universeId}"
name: "${universeName}"
description: ""
version: "1.0.0"
defaultLanguage: "id"
bibleRoot: "./bible"

characters:
  - id: "protagonist"
    name: "Protagonist"
    role: "PROTAGONIST"
    displayName: "Protagonist"
    description: "Main character of the story"
    coreTraits: ["brave", "curious"]
    coreWeakness: "Overconfidence"
    voiceGuide: "./bible/01-character-bible/voice-protagonist.md"
    bibleRef: "./bible/01-character-bible/protagonist.md"
    metadata: {}

regions:
  - id: "main-region"
    name: "Main Region"
    description: "Primary setting of the story"
    cultureGuide: "./bible/02-world-bible/culture-main-region.md"
    geography: "./bible/02-world-bible/geography-main-region.md"
    metadata: {}

canonRules:
  - ruleId: "no-violence"
    name: "No Graphic Violence"
    description: "Content must be appropriate for all ages"
    ruleType: "BANNED_WORD"
    pattern: "\\b(kill|murder|blood|gore)\\b"
    severity: "ERROR"
    isActive: true
    metadata: {}
  - ruleId: "weakness-consequence"
    name: "Weakness Must Have Consequence"
    description: "Character weaknesses must have narrative consequences"
    ruleType: "CHARACTER_CONSISTENCY"
    severity: "WARNING"
    isActive: true
    metadata:
      llmJudgePrompt: "Check if character weaknesses lead to meaningful consequences"

aiProviders:
  creativeGeneration: "anthropic:claude-3-5-sonnet-20241022"
  planning: "openai:gpt-4o-2024-08-06"
  validation: "anthropic:claude-3-5-haiku-20241022"
  embedding: "cohere:embed-multilingual-v3"
  imagePrompt: "openai:gpt-4o-2024-08-06"
  codeGeneration: "anthropic:claude-3-5-sonnet-20241022"

generationDefaults:
  sceneTargetLines: 10
  episodeTargetScenes: 6
  temperature: 0.7
  maxRetries: 2
`;

  await fs.writeFile(path.join(targetDir, 'universe.yaml'), manifest, 'utf-8');
}

/**
 * Create placeholder bible files
 */
async function createPlaceholderBibleFiles(
  biblePath: string,
  universeId: string,
  universeName: string
): Promise<void> {
  const placeholders = {
    '01-character-bible/character-overview.md': `# Character Overview: ${universeName}

## Core Cast

### Protagonist
- **ID**: protagonist
- **Name**: Protagonist
- **Role**: PROTAGONIST
- **Archetype**: Hero
- **Description**: The main character who drives the story forward
- **Core Traits**: [brave, curious, determined]
- **Core Weakness**: Overconfidence that leads to reckless decisions
- **Voice Guide**: ./voice-protagonist.md

---

*Add more characters following the template in templates/creator/character.md*
`,
    '01-character-bible/voice-protagonist.md': `# Voice Guide: Protagonist

## Tone
Optimistic and determined, with moments of vulnerability

## Vocabulary
- adventure, discovery, courage, friendship, wonder
- Technical terms related to their expertise

## Speech Patterns
- Uses rhetorical questions when thinking
- Speaks in short, punchy sentences during action
- Tends to explain things enthusiastically

## Catchphrases
- "Let's figure this out!"
- "There's always a way."

## Emotional Range
- **Joy**: Expressive, shares excitement openly
- **Fear**: Internalizes, shows through hesitation
- **Anger**: Cold and focused, not explosive
- **Sadness**: Quiet, processes alone before sharing
`,
    '02-world-bible/world-overview.md': `# World Overview: ${universeName}

## Setting
${universeName} takes place in a vibrant world filled with wonder and adventure.

## Geography
- **Main Region**: Primary setting of the story
- **Connected Regions**: Areas accessible from the main region

## Culture
- **Languages**: Common tongue, regional dialects
- **Customs**: Festival traditions, coming-of-age rituals
- **Beliefs**: Core values that shape society

## History
### Timeline
- **Ancient Era**: Foundational events
- **Recent History**: Events leading to current story

## Key Locations
1. **Starting Location** - Where the story begins
2. **Major Landmark** - Significant location
3. **Hidden Area** - Secret location revealed later

---
*Expand using templates in templates/creator/world.md*
`,
    '03-story-bible/story-overview.md': `# Story Overview: ${universeName}

## Logline
A compelling one-sentence summary of the story.

## Synopsis
A paragraph describing the main conflict, stakes, and journey.

## Themes
- Primary Theme: Growth through adversity
- Secondary Theme: Power of friendship
- Tertiary Theme: Balance between tradition and progress

## Genre
- Primary: Adventure
- Secondary: Fantasy
- Tone: Hopeful with moments of tension

## Structure
- **Acts**: 3
- **Seasons Planned**: 1
- **Episodes per Season**: 10

## Main Characters
- Protagonist (protagonist)

## Key Locations
- Main Region (main-region)

## Plot Points
1. **Inciting Incident**: Event that disrupts status quo
2. **First Threshold**: Commitment to journey
3. **Midpoint**: Major revelation or reversal
4. **Climax**: Ultimate confrontation
5. **Resolution**: New equilibrium established

---
*Expand using templates in templates/creator/story.md*
`,
    '04-visual-bible/style-guide.md': `# Visual Style Guide: ${universeName}

## Color Palette
### Primary Colors
- **Primary**: #HEX - Description
- **Secondary**: #HEX - Description
- **Accent**: #HEX - Description

### Mood Colors
- **Day**: Warm, bright tones
- **Night**: Cool, mysterious tones
- **Action**: High contrast, saturated
- **Emotional**: Muted, focused palette

## Character Design
### Protagonist
- **Silhouette**: Distinctive and recognizable
- **Color Scheme**: Matches personality
- **Key Features**: Signature accessory/element

## Environment Design
- **Architecture Style**: Description
- **Lighting**: Time-of-day variations
- **Atmosphere**: Weather, particles, mood

## Animation/Art Style
- **Line Weight**: Clean/thick/expressive
- **Shading**: Cel/soft/painted
- **Effects**: Particle style, magic/tech aesthetic

---
*Expand using templates in templates/creator/production.md*
`,
    '05-production-bible/production-notes.md': `# Production Bible: ${universeName}

## Technical Specifications
- **Format**: Episodic series
- **Runtime**: 22 minutes per episode
- **Aspect Ratio**: 16:9
- **Resolution**: 1920x1080 minimum

## Pipeline
- **Writing**: Script format (Final Draft / Fountain)
- **Storyboarding**: Digital (Toon Boom / Storyboard Pro)
- **Animation**: 2D / 3D hybrid
- **Compositing**: After Effects / Nuke

## Assets
- **Character Rigs**: Modular, expression-driven
- **Backgrounds**: Layered for parallax
- **Props**: Reusable library

## Audio
- **Music**: Themes per character/location
- **SFX**: Custom library + Foley
- **Voice**: Direction notes per character

## Quality Control
- **Canon Review**: Every episode
- **Visual Consistency**: Model sheets enforced
- **Audio Sync**: Frame-accurate

---
*Expand using templates in templates/creator/production.md*
`,
  };

  for (const [relPath, content] of Object.entries(placeholders)) {
    const fullPath = path.join(biblePath, relPath);
    await fs.ensureDir(path.dirname(fullPath));
    await fs.writeFile(fullPath, content, 'utf-8');
  }
}

/**
 * Create .gitignore for universe
 */
async function createGitignore(targetDir: string): Promise<void> {
  const gitignore = `# Dependencies
node_modules/

# Build outputs
dist/
build/
*.tsbuildinfo

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# Test coverage
coverage/

# Temporary files
*.tmp
*.temp
.cache/

# Universe specific
# Keep bible files in git!
# universes/*/bible/**/*
`;

  await fs.writeFile(path.join(targetDir, '.gitignore'), gitignore, 'utf-8');
}

/**
 * Copy template files from packages/templates
 */
export async function copyTemplateFiles(
  targetDir: string,
  templateName: string = 'suro-buya'
): Promise<void> {
  const templateSrc = path.join(TEMPLATE_SOURCE, 'src');
  const templateDest = path.join(targetDir, 'templates');
  
  if (await fs.pathExists(templateSrc)) {
    await fs.copy(templateSrc, templateDest, { overwrite: true });
  }
}

/**
 * Get list of available templates
 */
export async function getAvailableTemplates(): Promise<string[]> {
  const templatesDir = path.join(TEMPLATE_SOURCE, '..');
  if (!(await fs.pathExists(templatesDir))) {
    return ['suro-buya'];
  }
  
  const entries = await fs.readdir(templatesDir, { withFileTypes: true });
  return entries
    .filter(d => d.isDirectory())
    .map(d => d.name);
}